name: ci
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - helm-oci
          - kubeconform
          - netrc
          - oci-login
          - shellcheck

    steps:
      - name: ${{ matrix.module }}
        uses: dagger/dagger-for-github@8.0.0
        with:
          module: github.com/${{ github.repository }}/${{ matrix.module }}/tests@${{ github.ref }}
          call: all-tests
          cloud-token: ${{ secrets.DAGGER_CLOUD_TOKEN }}
          version: 0.17.0
