name: nsv
on:
  workflow_dispatch:
    inputs:
      projects:
        description: "the project(s) to be tagged, should be seperated by whitespace"
        required: true
        type: string

jobs:
  nsv:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Tag
        uses: purpleclay/nsv-action@v1
        with:
          projects: "${{ inputs.projects }}"
        env:
          GPG_PRIVATE_KEY: "${{ secrets.GPG_PRIVATE_KEY }}"
          GPG_PASSPHRASE: "${{ secrets.GPG_PASSPHRASE }}"
          GPG_TRUST_LEVEL: "${{ secrets.GPG_TRUST_LEVEL }}"
